import './globals.css';
import { IBM_Plex_Sans } from 'next/font/google';

const ibm = IBM_Plex_Sans({
	weight: ['100', '200', '300', '400', '500', '600', '700'],
	subsets: ['latin'],
});

export const metadata = {
	title: 'FEM | Equalizer',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={ibm.className}>{children}</body>
		</html>
	);
}
